"""
Pattern models for YouTube AI Research System.

This module defines Pydantic models for pattern statistics and reports
generated by the Pattern Intelligence Agent.
"""

from datetime import datetime
from typing import Optional, List, Dict, Any

from pydantic import BaseModel, Field


class PatternStatistic(BaseModel):
    """
    Represents aggregated statistics for a single pattern within a category.

    Attributes:
        category: Category of the pattern (e.g., 'hook_types', 'emotions')
        pattern: The specific pattern value (e.g., 'question', 'excited')
        count: Number of videos with this pattern
        percentage: Percentage of total videos (0.0-100.0)
        average_views: Average view count for videos with this pattern
        average_likes: Average like count for videos with this pattern
        average_comments: Average comment count for videos with this pattern
        average_duration: Average video duration in seconds
        highest_view_video: Video ID with highest views in this pattern
        lowest_view_video: Video ID with lowest views in this pattern
    """

    category: str = Field(..., description="Category of the pattern")
    pattern: str = Field(..., description="The specific pattern value")
    count: int = Field(..., ge=0, description="Number of videos with this pattern")
    percentage: float = Field(..., ge=0.0, le=100.0, description="Percentage of total videos")
    average_views: float = Field(default=0.0, description="Average view count")
    average_likes: float = Field(default=0.0, description="Average like count")
    average_comments: float = Field(default=0.0, description="Average comment count")
    average_duration: float = Field(default=0.0, description="Average duration in seconds")
    highest_view_video: Optional[str] = Field(default=None, description="Video ID with highest views")
    lowest_view_video: Optional[str] = Field(default=None, description="Video ID with lowest views")


class PatternReport(BaseModel):
    """
    Represents a complete pattern analysis report.

    Attributes:
        report_name: Name of the report
        created_at: When the report was generated
        total_videos: Total number of videos analyzed
        total_analyses: Total number of analyses processed
        average_confidence: Average confidence score across all analyses
        analysis_coverage: Percentage of videos with analysis (0.0-100.0)
        statistics: List of pattern statistics
        recommendations: List of actionable recommendations
        json_report: Full JSON report data
    """

    report_name: str = Field(..., description="Name of the report")
    created_at: Optional[datetime] = Field(default=None, description="Report generation time")
    total_videos: int = Field(default=0, description="Total videos in dataset")
    total_analyses: int = Field(default=0, description="Total analyses processed")
    average_confidence: float = Field(default=0.0, description="Average confidence score")
    analysis_coverage: float = Field(default=0.0, description="Percentage of videos with analysis")
    statistics: List[PatternStatistic] = Field(default_factory=list, description="Pattern statistics")
    recommendations: List[str] = Field(default_factory=list, description="Actionable recommendations")
    json_report: Dict[str, Any] = Field(default_factory=dict, description="Full JSON report data")


class PatternSummary(BaseModel):
    """
    Summary of pattern analysis results for display.

    Attributes:
        videos_analyzed: Number of videos analyzed
        patterns_found: Total number of unique patterns discovered
        reports_saved: Number of reports saved
        top_hook: Most common hook type
        top_emotion: Most common emotion
        top_story_structure: Most common story structure
        top_thumbnail_pattern: Most common thumbnail pattern
        top_title_formula: Most common title formula
    """

    videos_analyzed: int = Field(default=0, description="Videos analyzed")
    patterns_found: int = Field(default=0, description="Unique patterns found")
    reports_saved: int = Field(default=0, description="Reports saved")
    top_hook: Optional[str] = Field(default=None, description="Top hook type")
    top_emotion: Optional[str] = Field(default=None, description="Top emotion")
    top_story_structure: Optional[str] = Field(default=None, description="Top story structure")
    top_thumbnail_pattern: Optional[str] = Field(default=None, description="Top thumbnail pattern")
    top_title_formula: Optional[str] = Field(default=None, description="Top title formula")